// <auto-generated />
using System;
using AliceRestaurant.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AliceRestaurant.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240330135537_update_table")]
    partial class update_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AliceRestaurant.Models.DeliveryMenu", b =>
                {
                    b.Property<int>("DeliveryMenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliveryMenuId"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("MenuName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentMenuId")
                        .HasColumnType("int");

                    b.HasKey("DeliveryMenuId");

                    b.HasIndex("ParentMenuId");

                    b.ToTable("DeliveryMenus");

                    b.HasData(
                        new
                        {
                            DeliveryMenuId = 1,
                            CreatedOn = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6704),
                            LastUpdated = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6703),
                            MenuName = "Delivery 1"
                        },
                        new
                        {
                            DeliveryMenuId = 2,
                            CreatedOn = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6707),
                            LastUpdated = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6707),
                            MenuName = "Delivery 2"
                        },
                        new
                        {
                            DeliveryMenuId = 3,
                            CreatedOn = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6709),
                            LastUpdated = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6709),
                            MenuName = "Sub Delivery A",
                            ParentMenuId = 1
                        },
                        new
                        {
                            DeliveryMenuId = 4,
                            CreatedOn = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6711),
                            LastUpdated = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6710),
                            MenuName = "Sub Delivery B",
                            ParentMenuId = 1
                        },
                        new
                        {
                            DeliveryMenuId = 5,
                            CreatedOn = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6712),
                            LastUpdated = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6712),
                            MenuName = "Sub Delivery C",
                            ParentMenuId = 2
                        });
                });

            modelBuilder.Entity("AliceRestaurant.Models.DineInMenu", b =>
                {
                    b.Property<int>("DineInMenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DineInMenuId"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("MenuName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentMenuId")
                        .HasColumnType("int");

                    b.HasKey("DineInMenuId");

                    b.HasIndex("ParentMenuId");

                    b.ToTable("DineInMenus");

                    b.HasData(
                        new
                        {
                            DineInMenuId = 1,
                            CreatedOn = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6455),
                            LastUpdated = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6441),
                            MenuName = "DineIn 1"
                        },
                        new
                        {
                            DineInMenuId = 2,
                            CreatedOn = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6459),
                            LastUpdated = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6459),
                            MenuName = "DineIn 2"
                        },
                        new
                        {
                            DineInMenuId = 3,
                            CreatedOn = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6460),
                            LastUpdated = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6460),
                            MenuName = "Sub DineIn A",
                            ParentMenuId = 1
                        },
                        new
                        {
                            DineInMenuId = 4,
                            CreatedOn = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6462),
                            LastUpdated = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6461),
                            MenuName = "Sub DineIn B",
                            ParentMenuId = 1
                        },
                        new
                        {
                            DineInMenuId = 5,
                            CreatedOn = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6463),
                            LastUpdated = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6463),
                            MenuName = "Sub DineIn C",
                            ParentMenuId = 2
                        });
                });

            modelBuilder.Entity("AliceRestaurant.Models.Dish", b =>
                {
                    b.Property<int>("DishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DishId"));

                    b.Property<string>("Allergy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeliveryMenuId")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DineInMenuId")
                        .HasColumnType("int");

                    b.Property<string>("DineInType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("KoreanName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SellingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DishId");

                    b.HasIndex("DeliveryMenuId");

                    b.HasIndex("DineInMenuId");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            DishId = 1,
                            Allergy = "Allergy",
                            CreatedOn = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6934),
                            DeliveryMenuId = 1,
                            DeliveryType = "Delivery",
                            Description = "Dish One Description",
                            DineInMenuId = 1,
                            DineInType = "DineIn",
                            DishName = "Dish 1",
                            EnglishName = "Dish One",
                            ImageUrl = "https://www.google.com",
                            IsAvailable = true,
                            KoreanName = "Dish One",
                            LastUpdated = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6933),
                            Price = 10m,
                            RestaurantId = 1,
                            SellingDate = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6940),
                            ShortName = "D1"
                        },
                        new
                        {
                            DishId = 2,
                            Allergy = "Allergy",
                            CreatedOn = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6943),
                            DeliveryMenuId = 2,
                            DeliveryType = "Delivery",
                            Description = "Dish Two Description",
                            DineInMenuId = 2,
                            DineInType = "DineIn",
                            DishName = "Dish 2",
                            EnglishName = "Dish Two",
                            ImageUrl = "https://www.google.com",
                            IsAvailable = true,
                            KoreanName = "Dish Two",
                            LastUpdated = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6942),
                            Price = 20m,
                            RestaurantId = 2,
                            SellingDate = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6946),
                            ShortName = "D2"
                        },
                        new
                        {
                            DishId = 3,
                            Allergy = "Allergy",
                            CreatedOn = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6948),
                            DeliveryMenuId = 3,
                            DeliveryType = "Delivery",
                            Description = "Dish Three Description",
                            DineInMenuId = 3,
                            DineInType = "DineIn",
                            DishName = "Dish 3",
                            EnglishName = "Dish Three",
                            ImageUrl = "https://www.google.com",
                            IsAvailable = true,
                            KoreanName = "Dish Three",
                            LastUpdated = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6947),
                            Price = 30m,
                            RestaurantId = 3,
                            SellingDate = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6950),
                            ShortName = "D3"
                        });
                });

            modelBuilder.Entity("AliceRestaurant.Models.Restaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestaurantId"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RestaurantId");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            RestaurantId = 1,
                            CreatedOn = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6755),
                            LastUpdated = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6755),
                            Name = "Restaurant 1"
                        },
                        new
                        {
                            RestaurantId = 2,
                            CreatedOn = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6759),
                            LastUpdated = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6758),
                            Name = "Restaurant 2"
                        },
                        new
                        {
                            RestaurantId = 3,
                            CreatedOn = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6760),
                            LastUpdated = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6760),
                            Name = "Restaurant 3"
                        });
                });

            modelBuilder.Entity("AliceRestaurant.Models.RestaurantDish", b =>
                {
                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("DishId", "RestaurantId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("RestaurantDishes");

                    b.HasData(
                        new
                        {
                            DishId = 1,
                            RestaurantId = 1,
                            CreatedOn = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6850),
                            LastUpdated = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6847)
                        },
                        new
                        {
                            DishId = 2,
                            RestaurantId = 1,
                            CreatedOn = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6853),
                            LastUpdated = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6852)
                        },
                        new
                        {
                            DishId = 3,
                            RestaurantId = 1,
                            CreatedOn = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6854),
                            LastUpdated = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6854)
                        },
                        new
                        {
                            DishId = 1,
                            RestaurantId = 2,
                            CreatedOn = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6856),
                            LastUpdated = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6856)
                        },
                        new
                        {
                            DishId = 2,
                            RestaurantId = 2,
                            CreatedOn = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6857),
                            LastUpdated = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6857)
                        },
                        new
                        {
                            DishId = 3,
                            RestaurantId = 3,
                            CreatedOn = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6859),
                            LastUpdated = new DateTime(2024, 3, 30, 20, 55, 36, 875, DateTimeKind.Local).AddTicks(6858)
                        });
                });

            modelBuilder.Entity("AliceRestaurant.Models.DeliveryMenu", b =>
                {
                    b.HasOne("AliceRestaurant.Models.DeliveryMenu", "ParentMenu")
                        .WithMany("DeliveryMenus")
                        .HasForeignKey("ParentMenuId");

                    b.Navigation("ParentMenu");
                });

            modelBuilder.Entity("AliceRestaurant.Models.DineInMenu", b =>
                {
                    b.HasOne("AliceRestaurant.Models.DineInMenu", "ParentMenu")
                        .WithMany("DineInMenus")
                        .HasForeignKey("ParentMenuId");

                    b.Navigation("ParentMenu");
                });

            modelBuilder.Entity("AliceRestaurant.Models.Dish", b =>
                {
                    b.HasOne("AliceRestaurant.Models.DeliveryMenu", "DeliveryMenu")
                        .WithMany("Dishes")
                        .HasForeignKey("DeliveryMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AliceRestaurant.Models.DineInMenu", "DineInMenu")
                        .WithMany("Dishes")
                        .HasForeignKey("DineInMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryMenu");

                    b.Navigation("DineInMenu");
                });

            modelBuilder.Entity("AliceRestaurant.Models.RestaurantDish", b =>
                {
                    b.HasOne("AliceRestaurant.Models.Dish", "Dish")
                        .WithMany("RestaurantDishes")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AliceRestaurant.Models.Restaurant", "Restaurant")
                        .WithMany("RestaurantDishes")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("AliceRestaurant.Models.DeliveryMenu", b =>
                {
                    b.Navigation("DeliveryMenus");

                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("AliceRestaurant.Models.DineInMenu", b =>
                {
                    b.Navigation("DineInMenus");

                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("AliceRestaurant.Models.Dish", b =>
                {
                    b.Navigation("RestaurantDishes");
                });

            modelBuilder.Entity("AliceRestaurant.Models.Restaurant", b =>
                {
                    b.Navigation("RestaurantDishes");
                });
#pragma warning restore 612, 618
        }
    }
}
