// <auto-generated />
using System;
using AliceRestaurant.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AliceRestaurant.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240402090149_seed_database")]
    partial class seed_database
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AliceRestaurant.Models.DeliveryCategory", b =>
                {
                    b.Property<int>("DeliveryCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliveryCategoryId"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("DeliveryCategoryId");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("DeliveryCategories");

                    b.HasData(
                        new
                        {
                            DeliveryCategoryId = 1,
                            CategoryName = "Delivery 1",
                            CreatedOn = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(9050),
                            LastUpdated = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(9051)
                        },
                        new
                        {
                            DeliveryCategoryId = 2,
                            CategoryName = "Delivery 2",
                            CreatedOn = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(9054),
                            LastUpdated = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(9054)
                        },
                        new
                        {
                            DeliveryCategoryId = 3,
                            CategoryName = "Sub Delivery A",
                            CreatedOn = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(9055),
                            LastUpdated = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(9055),
                            ParentCategoryId = 1
                        },
                        new
                        {
                            DeliveryCategoryId = 4,
                            CategoryName = "Sub Delivery B",
                            CreatedOn = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(9056),
                            LastUpdated = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(9056),
                            ParentCategoryId = 1
                        },
                        new
                        {
                            DeliveryCategoryId = 5,
                            CategoryName = "Sub Delivery C",
                            CreatedOn = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(9057),
                            LastUpdated = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(9057),
                            ParentCategoryId = 2
                        });
                });

            modelBuilder.Entity("AliceRestaurant.Models.DineInCategory", b =>
                {
                    b.Property<int>("DineInCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DineInCategoryId"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("DineInCategoryId");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("DineInCategories");

                    b.HasData(
                        new
                        {
                            DineInCategoryId = 1,
                            CategoryName = "DineIn 1",
                            CreatedOn = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(8859),
                            LastUpdated = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(8877)
                        },
                        new
                        {
                            DineInCategoryId = 2,
                            CategoryName = "DineIn 2",
                            CreatedOn = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(8879),
                            LastUpdated = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(8880)
                        },
                        new
                        {
                            DineInCategoryId = 3,
                            CategoryName = "Sub DineIn A",
                            CreatedOn = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(8881),
                            LastUpdated = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(8881),
                            ParentCategoryId = 1
                        },
                        new
                        {
                            DineInCategoryId = 4,
                            CategoryName = "Sub DineIn B",
                            CreatedOn = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(8882),
                            LastUpdated = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(8882),
                            ParentCategoryId = 1
                        },
                        new
                        {
                            DineInCategoryId = 5,
                            CategoryName = "Sub DineIn C",
                            CreatedOn = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(8883),
                            LastUpdated = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(8883),
                            ParentCategoryId = 2
                        });
                });

            modelBuilder.Entity("AliceRestaurant.Models.Dish", b =>
                {
                    b.Property<int>("DishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DishId"));

                    b.Property<string>("Allergy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeliveryCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DineInCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("DineInType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("KoreanName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SellingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DishId");

                    b.HasIndex("DeliveryCategoryId");

                    b.HasIndex("DineInCategoryId");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            DishId = 1,
                            Allergy = "Allergy",
                            CreatedOn = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(9185),
                            DeliveryCategoryId = 1,
                            DeliveryType = "Delivery",
                            Description = "Dish One Description",
                            DineInCategoryId = 1,
                            DineInType = "DineIn",
                            DishName = "Dish 1",
                            EnglishName = "Dish One",
                            ImageUrl = "https://www.google.com",
                            IsAvailable = true,
                            KoreanName = "Dish One",
                            LastUpdated = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(9187),
                            Price = 10m,
                            RestaurantId = 1,
                            ShortName = "D1"
                        },
                        new
                        {
                            DishId = 2,
                            Allergy = "Allergy",
                            CreatedOn = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(9188),
                            DeliveryCategoryId = 2,
                            DeliveryType = "Delivery",
                            Description = "Dish Two Description",
                            DineInCategoryId = 2,
                            DineInType = "DineIn",
                            DishName = "Dish 2",
                            EnglishName = "Dish Two",
                            ImageUrl = "https://www.google.com",
                            IsAvailable = true,
                            KoreanName = "Dish Two",
                            LastUpdated = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(9188),
                            Price = 20m,
                            RestaurantId = 2,
                            ShortName = "D2"
                        },
                        new
                        {
                            DishId = 3,
                            Allergy = "Allergy",
                            CreatedOn = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(9189),
                            DeliveryCategoryId = 3,
                            DeliveryType = "Delivery",
                            Description = "Dish Three Description",
                            DineInCategoryId = 3,
                            DineInType = "DineIn",
                            DishName = "Dish 3",
                            EnglishName = "Dish Three",
                            ImageUrl = "https://www.google.com",
                            IsAvailable = true,
                            KoreanName = "Dish Three",
                            LastUpdated = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(9189),
                            Price = 30m,
                            RestaurantId = 3,
                            ShortName = "D3"
                        });
                });

            modelBuilder.Entity("AliceRestaurant.Models.Restaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestaurantId"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RestaurantId");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            RestaurantId = 1,
                            CreatedOn = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(9117),
                            LastUpdated = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(9118),
                            Name = "Restaurant 1"
                        },
                        new
                        {
                            RestaurantId = 2,
                            CreatedOn = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(9119),
                            LastUpdated = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(9120),
                            Name = "Restaurant 2"
                        },
                        new
                        {
                            RestaurantId = 3,
                            CreatedOn = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(9120),
                            LastUpdated = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(9121),
                            Name = "Restaurant 3"
                        });
                });

            modelBuilder.Entity("AliceRestaurant.Models.RestaurantDish", b =>
                {
                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("DishId", "RestaurantId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("RestaurantDishes");

                    b.HasData(
                        new
                        {
                            DishId = 1,
                            RestaurantId = 1,
                            CreatedOn = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(9411),
                            LastUpdated = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(9412)
                        },
                        new
                        {
                            DishId = 2,
                            RestaurantId = 2,
                            CreatedOn = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(9414),
                            LastUpdated = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(9415)
                        },
                        new
                        {
                            DishId = 3,
                            RestaurantId = 3,
                            CreatedOn = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(9415),
                            LastUpdated = new DateTime(2024, 4, 2, 16, 1, 49, 333, DateTimeKind.Local).AddTicks(9416)
                        });
                });

            modelBuilder.Entity("AliceRestaurant.Models.DeliveryCategory", b =>
                {
                    b.HasOne("AliceRestaurant.Models.DeliveryCategory", "ParentCategory")
                        .WithMany("DeliveryCategories")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("AliceRestaurant.Models.DineInCategory", b =>
                {
                    b.HasOne("AliceRestaurant.Models.DineInCategory", "ParentCategory")
                        .WithMany("DineInCategories")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("AliceRestaurant.Models.Dish", b =>
                {
                    b.HasOne("AliceRestaurant.Models.DeliveryCategory", "DeliveryCategory")
                        .WithMany("Dishes")
                        .HasForeignKey("DeliveryCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AliceRestaurant.Models.DineInCategory", "DineInCategory")
                        .WithMany("Dishes")
                        .HasForeignKey("DineInCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryCategory");

                    b.Navigation("DineInCategory");
                });

            modelBuilder.Entity("AliceRestaurant.Models.RestaurantDish", b =>
                {
                    b.HasOne("AliceRestaurant.Models.Dish", "Dish")
                        .WithMany("RestaurantDishes")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AliceRestaurant.Models.Restaurant", "Restaurant")
                        .WithMany("RestaurantDishes")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("AliceRestaurant.Models.DeliveryCategory", b =>
                {
                    b.Navigation("DeliveryCategories");

                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("AliceRestaurant.Models.DineInCategory", b =>
                {
                    b.Navigation("DineInCategories");

                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("AliceRestaurant.Models.Dish", b =>
                {
                    b.Navigation("RestaurantDishes");
                });

            modelBuilder.Entity("AliceRestaurant.Models.Restaurant", b =>
                {
                    b.Navigation("RestaurantDishes");
                });
#pragma warning restore 612, 618
        }
    }
}
